### ISSUE TITLE
Глюк какой-то

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2020-8-forum#41]
При попытке создать пост наблюдаю такую картину в консоли:
```
http://localhost:8080/post/create: 20:40:40
TypeError: Cannot read property 'id' of undefined
    at D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\routes\post.js:43:45
    at Layer.handle [as handle_request] (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\layer.js:95:5)
    at D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Mazdaywik\Documents\Преподавание\УТП 2020\utp2020-8-forum\node_modules\express\lib\router\index.js:47:12)
```

**Comment by azmetovdt** [comment]
Проблема в том, что нет обработки запроса создания поста, когда пользователь не залогинен
